name: Build Slim Docker Image For Rhattox Workflows

on:
  push:
    branches:
      - main
      - feature/dev
    paths-ignore:
      - .github/workflows/**

env:
  IMAGE_NAME: "toolbox"
  APP_PATH: "./debian-toolbox"
jobs:
  build-and-deploy:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to DockerHub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get Image Version
        id: get-version
        run: |
          cd $APP_PATH
          echo "VERSION=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          cd $APP_PATH
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ steps.get-version.outputs.VERSION }} -f Dockerfile .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ steps.get-version.outputs.VERSION }}
